### ISSUE TITLE
init_glmpca_pois doesn't throw an error when one of the colSums or rowSums is equal to 0

### ISSUE THREAD

**Issue by eweine** [stephenslab/fastglmpca#10]
I accidentally ran the fit function on a matrix where some of the column sums were equal to zero. The error that was eventually thrown was confusing (it resulted from taking an svd of a matrix with infinite values). init_glmpca_pois should check that no rowSums or colSums are 0. I will take care of this.

**Comment by pcarbo** [comment]
More generally, would you get the error if a row or column had all the same value (e.g., a row or column of ones)?
