### ISSUE TITLE
Improve documentation for fit_glmpca_pois control parameters

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/fastglmpca#8]
Some of the documentation of the control parameters (e.g., "tol") is a bit confusing. The documentation just says that these parameters are fed to daarem, but ideally we would be able to document and explain them so that someone who didn't want to look at the daarem documentation could understand what they are doing.

**Comment by pcarbo** [comment]
@eweine Can you please take a look at the improvements to the documentation to see if the purpose of the daarem-related control settings is more clear now?

**Comment by eweine** [comment]
Much better, thanks!
