### ISSUE TITLE
Restore warning that is thrown when algorithm stops without convergence

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/fastglmpca#9]
At some point, there was a warning that warned the user if the algorithm stopped without convergence. It seems that this disappeared in the daarem overhaul (which I understand because perhaps that is a bit more difficult to implement with daarem). If possible, could we restore that warning message?

**Comment by pcarbo** [comment]
@eweine How's this?

```r
set.seed(1)
n <- 1000
p <- 500
K <- 3
dat  <- generate_glmpca_data_pois(n,p,K)
fit0 <- init_glmpca_pois(dat$Y,K)
fit  <- fit_glmpca_pois(dat$Y,fit0 = fit0,
                        control = list(maxiter = 10))
# Warning message:
# In fit_glmpca_pois_main_loop(LL, FF, Y, fixed_l, fixed_f, verbose,  :
#   fit_glmpca_pois failed to meet convergence criterion within 10 iterations
```

**Comment by eweine** [comment]
Looks good!
